### ISSUE TITLE
English spelling error!

### ISSUE THREAD

**Issue by jtagt** [LorittaBot/LorittaWebsite#5]
https://imgur.com/a/mLPp4

You said: Warn the user if they tries to execute an command in blacklisted channels.

Correct way: Warn the user if they try to execute a command in blacklisted channels.

**Comment by jtagt** [comment]
Also, the setting of changing languages needs to be saved so when you come back to the website it automatically goes to a certain language.

**Comment by MrPowerGamerBR** [comment]
Fixed, thanks!
